# Generated by Django 4.2.1 on 2023-06-08 17:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articleapp', '0006_views'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='views',
            unique_together={('user', 'article')},
        ),
    ]
