# Generated by Django 4.2.2 on 2023-06-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleapp', '0007_alter_views_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('can_read_article', 'Can read article')]},
        ),
    ]
